name: Update Changelog
on:
  push:
    branches:
      - release
    paths-ignore:
      - '**.md'


jobs:
  calculate_next_version:
    name: Calculate next version
    uses: codenamephp/workflows.common/.github/workflows/calculate-next-version.yml@1
  update_changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    needs: calculate_next_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          future_release: ${{ needs.calculate_next_version.outputs.version }}
          release_branch: 'release'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update changelog
          branch: changelog
          delete-branch: true
          title: '[CHANGELOG] Update changelog'


      - name: Merge pull request
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          pullRequestNumber: ${{ steps.cpr.outputs.pull-request-number }}
          intervalSeconds: 5