name: Prepare Release
on:
  merge_group:
    types:
      - checks_requested

jobs:
  calculate_next_version:
    uses: codenamephp/workflows.common/.github/workflows/calculate-next-version.yml@1
  update_changelog:
    uses: codenamephp/workflows.common/.github/workflows/update-changelog.yml@1
    needs: calculate_next_version
    with:
      ref: ${{github.ref_name}}
      future-release: ${{ needs.calculate_next_version.outputs.version }}
      release-branch: 'release'